/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AlbumokJpaController;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import model.Albumok;

/**
 *
 * @author maximuse
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        autoload();
    }

    private void autoload() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/view/img/icon.jpg"));
        loadData();
    }
    
    private void loadData() {
        this.emf = Persistence.createEntityManagerFactory("NeotonPU");
        this.ajc = new AlbumokJpaController(emf);
        this.albumok = new ArrayList<>();
        this.albumok = ajc.findAlbumokEntities();
        
        this.jComboBox1.removeAllItems();
        this.jComboBox1.addItem("- Kérem válasszon albumot! -");
        
        for (Albumok album : this.albumok) {
            this.jComboBox1.addItem(album.getNev());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        boritoLabel = new javax.swing.JLabel();
        cimLabel = new javax.swing.JLabel();
        evLabel = new javax.swing.JLabel();
        frissitesButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nevField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        evSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        kepField = new javax.swing.JTextField();
        mentesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Neoton");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        boritoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/bakelit.png"))); // NOI18N

        cimLabel.setText("jLabel2");

        evLabel.setText("jLabel3");

        frissitesButton.setText("Frissítés");
        frissitesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        frissitesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frissitesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(frissitesButton))
                    .addComponent(boritoLabel)
                    .addComponent(cimLabel)
                    .addComponent(evLabel))
                .addContainerGap(612, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frissitesButton))
                .addGap(18, 18, 18)
                .addComponent(boritoLabel)
                .addGap(18, 18, 18)
                .addComponent(cimLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(evLabel)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Albumok", jPanel1);

        jLabel1.setText("Név:");

        nevField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nevFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Év:");

        evSpinner.setModel(new javax.swing.SpinnerNumberModel(1950, 1950, 2010, 1));

        jLabel3.setText("Kép:");

        kepField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kepFieldActionPerformed(evt);
            }
        });

        mentesButton.setText("Mentés");
        mentesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mentesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mentesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mentesButton)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nevField)
                        .addComponent(kepField)
                        .addComponent(evSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                .addContainerGap(435, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nevField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(evSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)))
                .addGap(26, 26, 26)
                .addComponent(mentesButton)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Új album hozzáadása", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        int index = this.jComboBox1.getSelectedIndex();
        
        if (index > 0) {
            try {
                this.boritoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/" + this.albumok.get(index - 1).getBorito())));
            }
            catch(Exception e) {
                this.boritoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/bakelit.png")));
            }
            
            this.cimLabel.setText(this.albumok.get(index - 1).getNev());
            this.evLabel.setText(this.albumok.get(index - 1).getEv() + "");
        }
        else {
            this.boritoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/bakelit.png")));
            this.cimLabel.setText("");
            this.evLabel.setText("");
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void nevFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nevFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nevFieldActionPerformed

    private void kepFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kepFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kepFieldActionPerformed

    private void mentesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mentesButtonActionPerformed
        String nev = this.nevField.getText();
        int ev = Integer.parseInt(this.evSpinner.getValue() + "");
        String kep = this.kepField.getText();
        
        if (nev.equals("")) {
            JOptionPane.showMessageDialog(null, "Nem adta meg a nevet!");
        }
        else if (kep.equals("")) {
            JOptionPane.showMessageDialog(null, "Nem adta meg a kép nevét!");
        }
        else {
            Albumok ujAlbum = new Albumok();
            ujAlbum.setNev(nev);
            ujAlbum.setEv(ev);
            ujAlbum.setBorito(kep);
            this.ajc.create(ujAlbum);
            
            JOptionPane.showMessageDialog(null, "Sikeres mentés!");
            
            loadData();
        }
    }//GEN-LAST:event_mentesButtonActionPerformed

    private void frissitesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frissitesButtonActionPerformed
        loadData();
    }//GEN-LAST:event_frissitesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boritoLabel;
    private javax.swing.JLabel cimLabel;
    private javax.swing.JLabel evLabel;
    private javax.swing.JSpinner evSpinner;
    private javax.swing.JButton frissitesButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField kepField;
    private javax.swing.JButton mentesButton;
    private javax.swing.JTextField nevField;
    // End of variables declaration//GEN-END:variables
    private EntityManagerFactory emf;
    private AlbumokJpaController ajc;
    private List<Albumok> albumok;
    
}